#! /bin/bash

# 定义要修改的内容
FILE="/etc/sysconfig/network-scripts/ifcfg-enos6"
IPAD="192.168.82.38"
NETMS="255.255.255.192"

sed -i 's/BOOTPROTO=dhcp/BOOTPROTO=static/g' $FILE
sed -i 's/ONBOOT=no/ONBOOT=yes/g' $FILE

# 在sed中要引用变量需要使用双引号,$符号此时需在前面用\进行转义
# 新增IP地址和掩码的场景
sed -i "\$a\IPADDR=$IPAD" $FILE
sed -i "\$a\NETMASK=$NETMS" $FILE

# 修改IP地址和掩码的场景
# 在sed中要引用变量需要使用双引号
ipaddr=$(cat $FILE | grep IPADDR)
sed -i "s/$ipaddr/IPADDR=$IPAD/g" $FILE

netmask=$(cat $FILE | grep NETMASK)
sed -i "s/$netmask/NETMASK=$NETMS/g" $FILE
